### ISSUE TITLE
Confused by Section

### ISSUE THREAD

**Issue by verbalshadow** [YeOldeDM/lets-godot-roguelike#61]
I feel the thing section of step three is very confusing. Am I supposed to be following the instructions here or are you talking about what we are trying to achieve?

**Comment by YeOldeDM** [comment]
https://github.com/YeOldeDM/lets-godot-roguelike/blob/verbfix/posts/step-3-things.md#generalization  

I reworded the Generalization concept to sound less like instructions, it should be presented as an idea to set the frame of the instructions to come.  
I am not sure if this is exactly what OP is talking about, though. Review and confirm, please!

**Comment by verbalshadow** [comment]
Yes, this clears the problem up.
