### ISSUE TITLE
incorrect script for blocking to work

### ISSUE THREAD

**Issue by verbalshadow** [YeOldeDM/lets-godot-roguelike#63]
In step 3 right above the step code block. Thing does not have a step function only player does.

Now Thing.step() can check for "not blocked cells" instead of just "floor" cells.

should be:

Now Player.step() can check for "not blocked cells" instead of just "floor" cells.

**Comment by YeOldeDM** [comment]
`step()` was supposed to be a method of Thing, but come to think of it, Things don't need to Step, just the Player, for now...
I changed the text in the article to describe `step()` as coming from Player and not Thing.
